/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.conexion.conectar;

/**
 *
 * @author Enzo
 */
public class MostrarClientes extends javax.swing.JFrame {
    DefaultTableModel model;
    String cod,ape,nomb,tel,iiva;
    public MostrarClientes() {
        initComponents();
        setSize(656, 600);
        setTitle("Lista de Clientes");
        setLocationRelativeTo(null);
        cargar("");
        //deshabilitar();
        
    }
    
    void cargar(String valor){

    String [] titulos={"Codigo","Nombre","Apellido","Telefono","IVA"};
        String [] registros = new String[5];
        String sql = "SELECT * FROM clientes WHERE cli_dni LIKE '%"+valor+"%' ORDER BY cli_dni ASC";
        model = new DefaultTableModel (null,titulos);
        conectar cc=new conectar();
        Connection cn= cc.conexion();
        try {
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()){
            registros[0]=rs.getString("cli_dni");
            registros[1]=rs.getString("cli_nom");
            registros[2]=rs.getString("cli_ap");
            registros[3]=rs.getString("cli_tel");
            registros[4]=rs.getString("cli_iva");
            model.addRow(registros);
        }
        t_tabclientes.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e);
        }
    }
    /*void deshabilitar(){
        cli_num.setEnabled(false);
        cli_ap.setEnabled(false);
        cli_nom.setEnabled(false);
        cli_tel.setEnabled(false);
        combocli_iva.setEnabled(false);
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_tabclientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cli_buscar = new javax.swing.JTextField();
        btn_cmostrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        t_tabclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        t_tabclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_tabclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_tabclientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 620, 382);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));
        jPanel3.setLayout(null);
        jPanel3.add(cli_buscar);
        cli_buscar.setBounds(16, 22, 122, 20);

        //btn_cmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/iconos/1438381115_x-office-spreadsheet.png"))); // NOI18N
        btn_cmostrar.setText("Mostrar Todo");
        jPanel3.add(btn_cmostrar);
        btn_cmostrar.setBounds(156, 16, 127, 33);
        
        btnVolver.setText("Volver");
        getContentPane().add(btnVolver);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnVolverActionPerformed(evt);
            }
        });
        btnVolver.setBounds(10, 540, 99, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 60, 299, 55);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Clientes");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 620, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 640, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnVolverActionPerformed(ActionEvent evt) {
		this.dispose();
	}

	private void t_tabclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_tabclientesMouseClicked
        
    }//GEN-LAST:event_t_tabclientesMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//      
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Clientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cmostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField cli_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_tabclientes;
    // End of variables declaration//GEN-END:variables
}
