package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import controlador.Coordinador;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends JFrame implements ActionListener {

	  private javax.swing.JButton botonConsultar;
	  private javax.swing.JButton botonRegistrar;
	  private javax.swing.JButton botonAgregarProductos;
	  private javax.swing.JButton botonGestionarProductos;
	  private javax.swing.JButton botonMostrarProductos;
	  private javax.swing.JButton botonAgregarVentas;
	  private javax.swing.JButton botonGestionarVentas;
	  private javax.swing.JButton botonMostrarVentas;
	  private javax.swing.JButton botonAgregarClientes;
	  private javax.swing.JButton botonGestionarClientes;
	  private javax.swing.JButton botonMostrarClientes;
	  private javax.swing.JLabel labelTitulo;
	  private javax.swing.JLabel labelTituloClientes;
	  private javax.swing.JLabel labelTituloVentas;
	  private javax.swing.JLabel labelTituloProductos;
	  private javax.swing.JLabel labelUsuarios;
	  private javax.swing.JLabel labelLogo;
	  
	  	  
	  private javax.swing.JPanel miPanelPrincipal,panelTitulo,panelInferior;
	  private javax.swing.JSeparator separador1,separador2,separador3,separador4;
	  private JMenuBar barraMenu;
	  private JMenu menu;
	  private JMenuItem itemOpciones;
  
	  private Dimension tamPantalla;
	  private Rectangle pantalla;
	  
	  private Coordinador miCoordinador;
	
	
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Ventana Principal");
        setSize(650, 350);
        setLocationRelativeTo(null);
        tamPantalla=Toolkit.getDefaultToolkit().getScreenSize();
        pantalla= new Rectangle(tamPantalla);
        setBounds(pantalla);
        addWindowListener(new WindowAdapter() {
        	
        	@Override
        	public void windowClosing(WindowEvent e) {
        		Object[] options = {"Continuar", "Cerrar"};
            	int n = JOptionPane.showOptionDialog(null,
                        "Seleccione un tipo de Usuario.\nSi sale el sistema se Cerrara","Confirmación",JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE,null,options,options[0]);
		       
            	if (n == JOptionPane.YES_OPTION){}
		        else if (n == JOptionPane.NO_OPTION) 
		        {
		        	System.exit(0);//Cerrar todo el sistema
		        }
        	}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelTituloClientes = new javax.swing.JLabel();
        labelTituloProductos = new javax.swing.JLabel();
        labelTituloVentas = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        botonAgregarProductos = new javax.swing.JButton();
        botonMostrarProductos = new javax.swing.JButton();
        botonGestionarProductos = new javax.swing.JButton();
        botonAgregarVentas = new javax.swing.JButton();
        botonMostrarVentas = new javax.swing.JButton();
        botonGestionarVentas = new javax.swing.JButton();
        botonAgregarClientes = new javax.swing.JButton();
        botonMostrarClientes = new javax.swing.JButton();
        botonGestionarClientes = new javax.swing.JButton();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        labelUsuarios = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 //       getContentPane().setLayout(null);

        //miPanelPrincipal.setBackground(transparent);
        miPanelPrincipal.setLayout(null);
        
        //panelTitulo.setBackground(Color.gray);
        //panelInferior.setBackground(Color.black);
      
        panelTitulo.setLayout(null);
        panelInferior.setLayout(new FlowLayout(FlowLayout.RIGHT));

        labelTitulo.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Bienvenido al Sistema");
        labelTitulo.setForeground(Color.black);
        //labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTitulo.add(labelTitulo);
       labelTitulo.setBounds(5, 5, 500, 50);
       
       labelTituloClientes.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
       labelTituloClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       labelTituloClientes.setText("Clientes");
       labelTituloClientes.setForeground(Color.black);
      // labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
       miPanelPrincipal.add(labelTituloClientes);
       labelTituloClientes.setBounds(5, 60, 190, 60);
       
       separador1.setBounds(5, 70, 1335, 10);
       miPanelPrincipal.add(separador1);
               
        botonConsultar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonConsultar.setText("CONSULTAR");
        miPanelPrincipal.add(botonConsultar);
        botonConsultar.setBounds(300, 530, 130, 40);
        botonConsultar.addActionListener(this);

        botonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonRegistrar.setText("REGISTRAR");
        miPanelPrincipal.add(botonRegistrar);
        botonRegistrar.setBounds(20, 530, 130, 40);
        botonRegistrar.addActionListener(this);
        
        botonAgregarClientes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonAgregarClientes.setText("Registrar Clientes");
        //botonAgregarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarcliente.png")));
        miPanelPrincipal.add(botonAgregarClientes);
        botonAgregarClientes.setBounds(20, 125, 185, 40);
        botonAgregarClientes.addActionListener(this);
        
        botonGestionarClientes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonGestionarClientes.setText("Gestionar Clientes");
        //botonModificarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarcliente.png")));
        miPanelPrincipal.add(botonGestionarClientes);
        botonGestionarClientes.setBounds(250, 125, 185, 40);
        botonGestionarClientes.addActionListener(this);
        
        botonMostrarClientes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonMostrarClientes.setText("Mostrar Clientes");
        //botonEliminarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarcliente.png")));
        miPanelPrincipal.add(botonMostrarClientes);
        botonMostrarClientes.setBounds(480, 125, 185, 40);
        botonMostrarClientes.addActionListener(this);
        
        separador2.setBounds(5, 185, 1335, 10);
        miPanelPrincipal.add(separador2);
        
        labelTituloProductos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTituloProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloProductos.setText("Productos");
        labelTituloProductos.setForeground(Color.black);
       // labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miPanelPrincipal.add(labelTituloProductos);
        labelTituloProductos.setBounds(5, 175, 190, 60);
        
        botonAgregarProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonAgregarProductos.setText("Registrar Producto");
        //botonAgregarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarproducto.png")));
        miPanelPrincipal.add(botonAgregarProductos);
        botonAgregarProductos.setBounds(20, 240, 185, 40);
        botonAgregarProductos.addActionListener(this);
        
        botonGestionarProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonGestionarProductos.setText("Gestionar Producto");
        //botonModificarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarproducto.png")));
        miPanelPrincipal.add(botonGestionarProductos);
        botonGestionarProductos.setBounds(250, 240, 185, 40);
        botonGestionarProductos.addActionListener(this);
        
        botonMostrarProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonMostrarProductos.setText("Mostrar Producto");
        //botonEliminarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarproducto.png")));
        miPanelPrincipal.add(botonMostrarProductos);
        botonMostrarProductos.setBounds(480, 240, 185, 40);
        botonMostrarProductos.addActionListener(this);
        
        separador3.setBounds(5, 300, 1335, 10);
        miPanelPrincipal.add(separador3);
        
        labelTituloVentas.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTituloVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloVentas.setText("Ventas");
        labelTituloVentas.setForeground(Color.black);
       // labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miPanelPrincipal.add(labelTituloVentas);
        labelTituloVentas.setBounds(5, 295, 190, 60);
        
        botonAgregarVentas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonAgregarVentas.setText("Agregar Ventas");
        //botonAgregarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarventas.png")));
        miPanelPrincipal.add(botonAgregarVentas);
        botonAgregarVentas.setBounds(20, 360, 185, 40);
        botonAgregarVentas.addActionListener(this);
        
        botonGestionarVentas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        //botonModificarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarventas.png")));
        botonGestionarVentas.setText("Gestionar Ventas");
        miPanelPrincipal.add(botonGestionarVentas);
        botonGestionarVentas.setBounds(250, 360, 185, 40);
        botonGestionarVentas.addActionListener(this);
        
        botonMostrarVentas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botonMostrarVentas.setText("Mostrar Ventas");
        //botonEliminarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarventas.png")));
        miPanelPrincipal.add(botonMostrarVentas);
        botonMostrarVentas.setBounds(480, 360, 185, 40);
        botonMostrarVentas.addActionListener(this);
        
        separador4.setBounds(5, 440, 1335, 10);
        miPanelPrincipal.add(separador4);
        labelUsuarios.setFont(new java.awt.Font("Verdana", 0, 25)); // NOI18N
        labelUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuarios.setText("Gestión de Usuarios");
        labelUsuarios.setForeground(Color.black);
       // labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miPanelPrincipal.add(labelUsuarios);
        labelUsuarios.setBounds(20, 440, 260, 60);
        
        /*labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png")));
        miPanelPrincipal.add(labelLogo);
        labelLogo.setBounds(206, 148, 192, 141);*/
        
        barraMenu =new JMenuBar();
        menu=new JMenu();
        itemOpciones =new JMenuItem();
        
        menu.setText("Opciones");
        itemOpciones.setText("Cambiar de Usuario");
        itemOpciones.addActionListener(this);
        
        menu.add(itemOpciones);
        barraMenu.add(menu);       
        
        setJMenuBar(barraMenu);
  
        miPanelPrincipal.setBounds(0, 0, 670, 350);
        panelTitulo.setBounds(0, 0, 1500, 70);
        panelInferior.setBounds(0, 667, 1350,40);
        miPanelPrincipal.add(panelTitulo);
        miPanelPrincipal.add(panelInferior);
        getContentPane().add(miPanelPrincipal);
        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void setCoordinador(Coordinador miCoordinador) {
		this.miCoordinador=miCoordinador;
	}

	public void asignarPrivilegios(String usuario) {
		labelTitulo.setText("Conectado como : "+usuario);
		
		if (usuario.equals("Administrador")) {
			botonConsultar.setVisible(true);
			botonAgregarClientes.setVisible(true);
			botonAgregarClientes.setBounds(20, 125, 185, 40);
			botonMostrarClientes.setVisible(true);
			botonMostrarClientes.setBounds(480, 125, 185, 40);
			botonGestionarClientes.setVisible(true);
			botonGestionarClientes.setBounds(250, 125, 185, 40);
			botonAgregarVentas.setVisible(true);
			botonAgregarVentas.setBounds(20, 360, 185, 40);
			botonGestionarVentas.setVisible(true);
			botonGestionarVentas.setBounds(250, 360, 185, 40);
			botonMostrarVentas.setVisible(true);
			botonMostrarVentas.setBounds(480, 360, 185, 40);
			botonAgregarProductos.setVisible(true);
			botonAgregarProductos.setBounds(20, 240, 185, 40);
			botonGestionarProductos.setVisible(true);
			botonGestionarProductos.setBounds(250, 240, 185, 40);
			botonMostrarProductos.setVisible(true);
			botonMostrarProductos.setBounds(480, 240, 185, 40);
			botonRegistrar.setVisible(true);
			labelUsuarios.setVisible(true);
			separador1.setVisible(true);
			labelTituloClientes.setVisible(true);
			separador2.setVisible(true);
			labelTituloProductos.setVisible(true);
		}
		if(usuario.equals("GerenteVentas")){
			botonConsultar.setVisible(false);
			botonAgregarClientes.setVisible(true);
			botonMostrarClientes.setVisible(true);
			botonGestionarClientes.setVisible(true);
			botonAgregarVentas.setVisible(true);
			botonGestionarVentas.setVisible(true);
			botonMostrarVentas.setVisible(true);
			botonAgregarProductos.setVisible(false);
			botonGestionarProductos.setVisible(false);
			botonMostrarProductos.setVisible(false);
			botonRegistrar.setVisible(true);
			labelUsuarios.setVisible(true);
			separador1.setVisible(true);
			labelTituloClientes.setVisible(true);
			separador2.setVisible(false);
			labelTituloProductos.setVisible(false);
			}
		if(usuario.equals("Deposito")){
			botonConsultar.setVisible(false);
			botonAgregarClientes.setVisible(false);
			botonMostrarClientes.setVisible(false);
			botonGestionarClientes.setVisible(false);
			botonAgregarVentas.setVisible(true);
			botonGestionarVentas.setVisible(true);
			botonMostrarVentas.setVisible(true);
			botonAgregarProductos.setVisible(true);
			botonGestionarProductos.setVisible(true);
			botonGestionarProductos.setBounds(250, 240, 185, 40);
			botonMostrarProductos.setVisible(true);
			botonRegistrar.setVisible(false);
			labelUsuarios.setVisible(false);
			separador1.setVisible(false);
			labelTituloClientes.setVisible(false);
			}
		if(usuario.equals("Usuario")){
			botonConsultar.setVisible(false);
			botonAgregarClientes.setVisible(true);
			botonMostrarClientes.setVisible(true);
			botonMostrarClientes.setBounds(250, 125, 185, 40);
			botonGestionarClientes.setVisible(false);
			botonAgregarVentas.setVisible(true);
			botonGestionarVentas.setVisible(false);
			botonMostrarVentas.setVisible(true);
			botonMostrarVentas.setBounds(250, 360, 185, 40);
			botonAgregarProductos.setVisible(false);
			botonGestionarProductos.setVisible(false);
			botonGestionarProductos.setBounds(20, 240, 185, 40);
			botonMostrarProductos.setVisible(true);
			botonMostrarProductos.setBounds(20, 240, 185, 40);
			botonRegistrar.setVisible(false);
			labelUsuarios.setVisible(false);
			separador1.setVisible(true);
			labelTituloClientes.setVisible(true);			
		}
		
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource()==itemOpciones) {
			miCoordinador.mostrarLogin();			
		}
		
		if (e.getSource()==botonRegistrar) {
			miCoordinador.mostrarVentanaRegistro();			
		}
		
		if (e.getSource()==botonConsultar) {
			miCoordinador.mostrarVentanaConsulta();			
		}
		if (e.getSource()==botonAgregarProductos) {
			RegistrarProductos miRegistrarProductos= new RegistrarProductos();
			miRegistrarProductos.setVisible(true);
		}		
		if (e.getSource()==botonGestionarProductos) {
			GestionarProductos miGestionarProductos= new GestionarProductos();
			miGestionarProductos.setVisible(true);
		}		
		if (e.getSource()==botonMostrarProductos) {
			MostrarProductos miMostrarProductos= new MostrarProductos();
			miMostrarProductos.setVisible(true);
		}
		if (e.getSource()==botonAgregarClientes) {
			RegistrarClientes miRegistrarClientes= new RegistrarClientes();
			miRegistrarClientes.setVisible(true);
		}
		if (e.getSource()==botonGestionarClientes) {
			GestionarClientes miGestionarClientes= new GestionarClientes();
			miGestionarClientes.setVisible(true);
		}
		if (e.getSource()==botonMostrarClientes) {
			MostrarClientes miMostrarClientes= new MostrarClientes();
			miMostrarClientes.setVisible(true);
		}
		if (e.getSource()==botonAgregarVentas) {			
			RegistrarVentas miRegistrarVentas= new RegistrarVentas();
			miRegistrarVentas.setVisible(true);
		}
		if (e.getSource()==botonGestionarVentas) {			
			GestionarVentas miGestionarVentas= new GestionarVentas();
			miGestionarVentas.setVisible(true);
		}
		if (e.getSource()==botonMostrarVentas) {
			MostrarVentas miMostrarVentas= new MostrarVentas();
			miMostrarVentas.setVisible(true);
		}
	}



  

}
